### ISSUE TITLE
Intellisense features not working

### ISSUE THREAD

**Issue by nathanlcarlson** [puppetlabs/puppet-vscode#822]
### What Versions are you running?

OS Version: Mac OS 12.5.1 (21G83)
VSCode Version: 1.71.2
Puppet Extension Version: v1.4.0
PDK Version: 2.5.0

### What You Are Seeing?

No Intellisense is working in my control repository. 

### What is Expected?

I'd like to have intellisense features working.

### How Did You Get This To Happen? (Steps to Reproduce)

Attempt to use the VSCode PDK extension in my organization's puppet control repo.

### Output Log
Found this in the logs (removed directory names):
```
ANY -- : SidecarQueue Thread: Calling sidecar with --action workspace_aggregate --local-workspace {control repo dir} --puppet-version=6.27.0 returned exitcode 1, ruby: warning: shebang line ending with \r may cause problems
{homedir}/.vscode/extensions/puppet.puppet-vscode-1.4.0/vendor/languageserver/lib/puppet-languageserver-sidecar/puppet_strings_helper.rb:147:in `block (3 levels) in populate_classes_from_yard_registry!': undefined method `join' for nil:NilClass (NoMethodError)
	from {homedir}/.vscode/extensions/puppet.puppet-vscode-1.4.0/vendor/languageserver/lib/puppet-languageserver-sidecar/puppet_strings_helper.rb:143:in `each'
	from {homedir}/.vscode/extensions/puppet.puppet-vscode-1.4.0/vendor/languageserver/lib/puppet-languageserver-sidecar/puppet_strings_helper.rb:143:in `block (2 levels) in populate_classes_from_yard_registry!'
	from {homedir}/.vscode/extensions/puppet.puppet-vscode-1.4.0/vendor/languageserver/lib/puppet-languageserver-sidecar/puppet_strings_helper.rb:128:in `each'
	from {homedir}/.vscode/extensions/puppet.puppet-vscode-1.4.0/vendor/languageserver/lib/puppet-languageserver-sidecar/puppet_strings_helper.rb:128:in `block in populate_classes_from_yard_registry!'
	from {homedir}/.vscode/extensions/puppet.puppet-vscode-1.4.0/vendor/languageserver/lib/puppet-languageserver-sidecar/puppet_strings_helper.rb:127:in `each'
	from {homedir}/.vscode/extensions/puppet.puppet-vscode-1.4.0/vendor/languageserver/lib/puppet-languageserver-sidecar/puppet_strings_helper.rb:127:in `populate_classes_from_yard_registry!'
	from {homedir}/.vscode/extensions/puppet.puppet-vscode-1.4.0/vendor/languageserver/lib/puppet-languageserver-sidecar/puppet_strings_helper.rb:102:in `populate_from_yard_registry!'
	from {homedir}/.vscode/extensions/puppet.puppet-vscode-1.4.0/vendor/languageserver/lib/puppet-languageserver-sidecar/puppet_strings_helper.rb:74:in `file_documentation'
	from {homedir}/.vscode/extensions/puppet.puppet-vscode-1.4.0/vendor/languageserver/lib/puppet-languageserver-sidecar/puppet_strings_helper.rb:10:in `file_documentation'
	from {homedir}/.vscode/extensions/puppet.puppet-vscode-1.4.0/vendor/languageserver/lib/puppet-languageserver-sidecar/puppet_helper.rb:93:in `block in retrieve_via_puppet_strings'
	from {homedir}/.vscode/extensions/puppet.puppet-vscode-1.4.0/vendor/languageserver/lib/puppet-languageserver-sidecar/puppet_helper.rb:92:in `each'
	from {homedir}/.vscode/extensions/puppet.puppet-vscode-1.4.0/vendor/languageserver/lib/puppet-languageserver-sidecar/puppet_helper.rb:92:in `retrieve_via_puppet_strings'
	from {homedir}/.vscode/extensions/puppet.puppet-vscode-1.4.0/vendor/languageserver/lib/puppet_languageserver_sidecar.rb:303:in `execute'
	from {homedir}/.vscode/extensions/puppet.puppet-vscode-1.4.0/vendor/languageserver/lib/puppet_languageserver_sidecar.rb:360:in `execute_and_output'
	from {homedir}/.vscode/extensions/puppet.puppet-vscode-1.4.0/vendor/languageserver/puppet-languageserver-sidecar:14:in `<main>'
```

**Comment by nathanlcarlson** [comment]
I put a local change in to bypass the problem. I doubt it is the correct solution, but it solves my issue:
```
$ vi {homedir}/.vscode/extensions/puppet.puppet-vscode-1.4.0/vendor/languageserver/lib/puppet-languageserver-sidecar/puppet_strings_helper.rb:143
...
          # Extract the class parameters
          unless item[:docstring][:tags].nil?
            item[:docstring][:tags].select { |tag| tag[:tag_name] == 'param' }.each do |tag|
              next if tag[:types].nil? # Skip nil
              param_name = tag[:name]
              obj.parameters[param_name] = {
                :doc  => tag[:text],
                :type => tag[:types].join(', ')
              }
            end
          end
 ...
```
