### ISSUE TITLE
LanguageServer crashes on startup

### ISSUE THREAD

**Issue by krisavi** [puppetlabs/puppet-vscode#859]
### What Versions are you running?

OS Version: Windows 10
VSCode Version: 1.85.0-insider
Puppet Extension Version: 1.5.0
PDK Version: 2.2.0

### What You Are Seeing?
VSCode reporting that it crashed for 3 times and not launching any more.

### What is Expected?
LanguageServer to load and not crash

### How Did You Get This To Happen? (Steps to Reproduce)
Updated VSCode and started to crash on startup

### Output Log

```
C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.4.10/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:72:in `require': c:/Users/dev/.vscode-insiders/extensions/puppet.puppet-vscode-1.5.0/vendor/languageserver/lib/puppet_languageserver.rb:67: syntax error, unexpected keyword_rescue, expecting keyword_end (SyntaxError)
    rescue LoadError
          ^
c:/Users/dev/.vscode-insiders/extensions/puppet.puppet-vscode-1.5.0/vendor/languageserver/lib/puppet_languageserver.rb:93: syntax error, unexpected keyword_rescue, expecting keyword_end
    rescue LoadError
          ^
c:/Users/dev/.vscode-insiders/extensions/puppet.puppet-vscode-1.5.0/vendor/languageserver/lib/puppet_languageserver.rb:106: syntax error, unexpected keyword_ensure, expecting end-of-input
  ensure
        ^
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.4.10/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	from c:/Users/dev/.vscode-insiders/extensions/puppet.puppet-vscode-1.5.0/vendor/languageserver/puppet-languageserver:12:in `<main>'
```

**Comment by jordanbreen28** [comment]
hey @krisavi, I suspect this is due to the outdated versions of ruby and pdk you are running with. 
Can you upgrade your pdk version to 2.7 (or greater, ideally 3.x) and let me know if the issue still persists?
Thanks

**Comment by krisavi** [comment]
I will try updating to 3.0, however Documentation seems to need updating if it does not support at least PDK 2.2.0
https://puppet-vscode.github.io/docs/getting-started/ states that 1.5.0 or greater.

**Comment by jordanbreen28** [comment]
@krisavi The site at https://puppet-vscode.github.io/docs/getting-started/ is in a bit of weird spot unfortunately, and will remain outdated whilst we try to claim ownership from the original author.
 
The bug you are seeing with PDK v2.7.1 was known to the puppet agent versions bundled in the pdk at that time, and will be rectified with an install of PDK v3.0.0. 

Unfortunately, the only thing I can suggest is that you downgrade your puppet-vscode extension to v1.4.2, which still uses a version of the language sever thats compatible with the versions of the pdk and puppet you were originally using, or upgrade to PDK v3
